force-app/main/default/objects/Log__e/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration in ms</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Time recording ended (if applicable)</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/ErrorId__c.field-meta.xml
<CustomField>
    <fullName>ErrorId__c</fullName>
    <label>Error ID</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/ExceptionLineNumber__c.field-meta.xml
<CustomField>
    <fullName>ExceptionLineNumber__c</fullName>
    <label>Exception Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <label>Exception Stack Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/IsBatch__c.field-meta.xml
<CustomField>
    <fullName>IsBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True when executed from a batch</description>
    <label>Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/IsFuture__c.field-meta.xml
<CustomField>
    <fullName>IsFuture__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Future</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/IsQueueable__c.field-meta.xml
<CustomField>
    <fullName>IsQueueable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Queueable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/IsScheduled__c.field-meta.xml
<CustomField>
    <fullName>IsScheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/IsTrigger__c.field-meta.xml
<CustomField>
    <fullName>IsTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns true if the current context for the Apex code is a trigger, not a Visualforce page, a Web service, or an executeanonymous() API call.</description>
    <label>Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/RunningUserId__c.field-meta.xml
<CustomField>
    <fullName>RunningUserId__c</fullName>
    <label>Running User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Time recording began (if applicable)</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/TriggerContext__c.field-meta.xml
<CustomField>
    <fullName>TriggerContext__c</fullName>
    <description>Possible values of the System.TriggerOperation enum are: BEFORE_INSERT, BEFORE_UPDATE, BEFORE_DELETE,AFTER_INSERT, AFTER_UPDATE, AFTER_DELETE, and AFTER_UNDELETE.</description>
    <label>Trigger Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/TriggerSize__c.field-meta.xml
<CustomField>
    <fullName>TriggerSize__c</fullName>
    <label>Trigger Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Log.cls
global with sharing class Log {

    // Set by user
    global Datetime startDate {get;set;}
    global Datetime endDate {get;set;}
    global String errorId {get;set;}
    global Id runningUserId {get;set;}

    // Trigger info
    global String triggerContext {get;set;}
    global Integer triggerSize {get;set;}
    global Boolean isTrigger {get;set;}

    // System info
    global Boolean isScheduled {get;set;}
    global Boolean isQueueable {get;set;}
    global Boolean isFuture {get;set;}
    global Boolean isBatch {get;set;}

    // Exception data
    global Integer exceptionLineNumber {get;set;}
    global String exceptionMessage {get;set;}
    global String exceptionStackTrace {get;set;}
    global String exceptionType {get;set;}

    // Specify additional data dynamically. Assumes that the API names match on the event and the
    // log recording object
    global Map<String,Object> additionalParamsByApiName {get;set;}


    global Log() {
        this.additionalParamsByApiName = new Map<String,Object>();
        this.errorId = LogService.createErrorId();
        setContextVariables();
    }

    global String getErrorId() {
        return this.errorId;
    }

    global void setContextVariables() {
        this.runningUserId = UserInfo.getUserId();
        this.isTrigger = Trigger.isExecuting;
        if(this.isTrigger) {
            this.triggerContext = String.valueOf(Trigger.operationType);
            this.triggerSize = Trigger.size;
        }
        this.isScheduled = System.isScheduled();
        this.isQueueable = System.isQueueable();
        this.isFuture = System.isFuture();
        this.isBatch = System.isBatch();
    }

    global void setExceptionInfo(Exception e) {
        this.exceptionLineNumber = e.getLineNumber();
        this.exceptionMessage = e.getMessage().abbreviate(255);
        this.exceptionStackTrace = e.getStackTraceString();
        this.exceptionType = e.getTypeName();
    }

    global Decimal getDuration() {
        if(startDate == null || endDate == null) {
            return null;
        }
        return endDate.getTime() - startDate.getTime();
    }

    global void emit() {
        Database.SaveResult result = Eventbus.publish(createLogEvent());
        System.debug(result);
    }

    global Log__e createLogEvent() {
        Log__e log = new Log__e();
        log.ErrorId__c = this.errorId;
        log.Duration__c = getDuration();
        log.StartDate__c = this.startDate;
        log.EndDate__c = this.endDate;
        log.ExceptionLineNumber__c = this.exceptionLineNumber;
        log.ExceptionMessage__c = this.exceptionMessage != null ? this.exceptionMessage.abbreviate(255) : null;
        log.ExceptionStackTrace__c = this.exceptionStackTrace != null ? this.exceptionStackTrace.abbreviate(255) : null;
        log.ExceptionType__c = this.exceptionType;
        log.IsBatch__c = this.isBatch;
        log.IsFuture__c = this.isFuture;
        log.IsQueueable__c = this.isQueueable;
        log.IsScheduled__c = this.isScheduled;
        log.IsTrigger__c = this.isTrigger;
        log.TriggerContext__c = this.triggerContext;
        log.TriggerSize__c = this.triggerSize;
        log.RunningUserId__c = this.runningUserId;
        for(String apiName : additionalParamsByApiName.keySet()) {
            log.put(apiName,additionalParamsByApiName.get(apiName));
        }
        return log;
    }

}