force-app/main/default/objects/Log__e/fields/RunningUserId__c.field-meta.xml
<CustomField>
    <fullName>RunningUserId__c</fullName>
    <label>Running User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogRecording__c/LogRecording__c.object-meta.xml
<CustomObject>
    <label>Log Recording</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Recordings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogRecording__c/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Running User when error occurred.</description>
    <inlineHelpText>Running User when error occurred.</inlineHelpText>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogRecordings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LogService.cls
global without sharing class LogService {

    public static void recordErrors(List<Log__e> logEvents) {
        List<LogRecording__c> logRecordings = new List<LogRecording__c>();
        Map<String, Schema.SObjectField> logEventFieldsByName = Schema.SObjectType.Log__e.fields.getMap();
        Map<String, Schema.SObjectField> logRecordingFieldsByName = Schema.SObjectType.LogRecording__c.fields.getMap();
        for(Log__e logEvent : logEvents) {
            LogRecording__c logRecording = new LogRecording__c();
            logRecording.RunningUser__c = logEvent.RunningUserId__c;
            for(String fieldName : logEventFieldsByName.keySet()) {
                if(logRecordingFieldsByName.containsKey(fieldName)
                        && logRecordingFieldsByName.get(fieldName).getDescribe().isUpdateable()) {
                    logRecording.put(fieldName,logEvent.get(fieldName));
                }
            }
            logRecordings.add(logRecording);
        }
        insert logRecordings;
    }

    public static String createErrorId() {
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
        return guid;
    }

}